---
# tasks file for motor_instalacion
- name: Importar tarea general para creacion ed grupos de relacion de confianza.
  include_tasks:
    file: /ansible/yml/tareas_generales/creacion_grupos.yml
  vars:
    usar_grupo_db: true

- name: Instalacion motor | Valida o crear directorio de Oracle home
  file:
    path: "{{ oracle_home }}"
    state: directory
    owner: ora19c
    group: oinstall
    mode: '0775'

- block:
  - name: Instalacion motor | Crea directorio temporal en oracle para logs
    file:
      path: "{{ oracle_tmp }}"
      state: directory
      owner: ora19c
      group: oinstall
      mode: '0775'

  - name: Instalacion motor | Envia y descomprimir el instalador del ora19c en la ruta de instalacion
    unarchive:
      src: "{{ instalador }}"
      dest: "{{ oracle_home }}"
      owner: ora19c
      group: oinstall
  when: inventory_hostname in groups['nodo1'] or inventory_hostname in groups['standalone']

- block:

  - name: Instalacion motor | Incluir tarea para cluster (NODO1)
    include_tasks: cluster.yml
    when: inventory_hostname in groups['nodo1']

  - name: Instalacion motor | Incluir tarea para Standalone
    include_tasks: standalone.yml
    when: inventory_hostname in groups['standalone']

  rescue:

  - name: Instalacion motor | Error controlado si hubo fallas con el instalador. 
    fail:
      msg: "Hubo un error en la ejecución por favor validar. [ X ] !!!"
    ignore_errors: true

  - meta: end_play

- name: Instalacion motor | Ejecuta script de root
  shell: "./root.sh"
  register: segunda_parte
  args:
    chdir: "{{ oracle_home }}"
    executable: /bin/sh

- debug:
    msg: "{{ segunda_parte.stdout }}"

- debug:
    msg: "Se ha completado con exito la instalacion del software del motor. ^ __ ^"
  changed_when: true
...
